server:
  port : 8081

cloud:
  aws:
    stack:
      auto: false
    region:
      static: us-east-1
      auto: false
    credentials:
      access-key: test-key
      secret-key: test-secret
    queue:
      uri: http://localhost:4566
      name: my-queue